### ISSUE TITLE
Invalid response

### ISSUE THREAD

**Issue by Pozaza** [prtolem/MailTM#11]
```
Traceback (most recent call last):
  File "c:\Users\Pozaza\Desktop\SD\sd\venv\lib\site-packages\gradio\routes.py", line 534, in predict
    output = await route_utils.call_process_api(
  File "c:\Users\Pozaza\Desktop\SD\sd\venv\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "c:\Users\Pozaza\Desktop\SD\sd\venv\lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "c:\Users\Pozaza\Desktop\SD\sd\venv\lib\site-packages\gradio\blocks.py", line 1183, in call_function
    prediction = await fn(*processed_input)
  File "c:\Users\Pozaza\Desktop\SD\sd\venv\lib\site-packages\gradio\utils.py", line 636, in async_wrapper
    response = await f(*args, **kwargs)
  File "c:\Users\Pozaza\Desktop\SD\sd\main.py", line 222, in try_get_key
    link = await get_link(mail[0], mail[1])
  File "c:\Users\Pozaza\Desktop\SD\sd\main.py", line 124, in get_link
    messages = await mailtm.get_messages(account.token, 1)
  File "c:\Users\Pozaza\Desktop\SD\sd\venv\lib\site-packages\mailtmapi\mailtm.py", line 130, in get_messages
    raise MailTMInvalidResponse
mailtmapi.utils.exceptions.MailTMInvalidResponse
```

and the code is just:

```python
async def get_link(mailtm: MailTM, account: Account):
    messages = await mailtm.get_messages(account.token, 1)
```

**Comment by Pozaza** [comment]
Ok i got it
just need to replace `account.token` to `account.token.token`
