### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by enriluis** [prtolem/MailTM#9]
I'm getting  this error in a simple example:

```
`from mailtm import MailTM
import asyncio
address = "myaccount"
password = "mypassword"

async def main() -> None:
    mailtm = MailTM()
    result = await mailtm.get_account_token(address, password)
    print(result)


if __name__ == '__main__':
    asyncio.run(main())
```

`

Traceback (most recent call last):
  File "mailtm.py", line 1, in <module>
    from mailtm import MailTM
  File "/home/lmb/MailTM/mailtm/__init__.py", line 1, in <module>
    from .mailtm import MailTM
  File "/home/lmb/MailTM/mailtm/mailtm.py", line 6, in <module>
    from .schemas.domains import Domains, Domain
  File "/home/lmb/MailTM/mailtm/schemas/domains.py", line 14, in <module>
    class Domains(BaseModel):
  File "/home/lmb/MailTM/mailtm/schemas/domains.py", line 16, in Domains
    hydra_member: list[Domain] = Field(alias="hydra:member")
TypeError: 'type' object is not subscriptable

**Comment by prtolem** [comment]
update the version from 
`pip install https://github.com/prtolem/MailTM/archive/branch.zip --force-reinstall`
